name: Analyze Code
run-name: Analyze Code for SpaceTraders PHP client.
on: pull_request
jobs:
  Run-Code-Quality-Checks:
    runs-on: ubuntu-24.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: readline, curl, redis, mbstring, intl
          ini-values: max_memory=512M
          tools: composer, cs2pr, phpstan, phpcs

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run PHPStan
        if: always()
        run: phpstan analyse --error-format=checkstyle| cs2pr

      - name: Run PHPCodeSniffer
        if: always()
        run: phpcs -q --report=checkstyle cli src | cs2pr

      - name: Run PHPArkitect
        if: always()
        run: vendor/bin/phparkitect check --format=json